<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\Position;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $positions = array(
            array('code' => '2', 'position_short_name' => ' ', 'position_name' => 'Accountant I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '3', 'position_short_name' => ' ', 'position_name' => 'Accountant II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '4', 'position_short_name' => ' ', 'position_name' => 'Accountant III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '5', 'position_short_name' => ' ', 'position_name' => 'Accountant IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '6', 'position_short_name' => ' ', 'position_name' => 'Admin Aide IV (Bookbinder II)Admin Aide IV (Bookbinder II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '7', 'position_short_name' => ' ', 'position_name' => 'Admin Asst VI (Computer Operator III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '8', 'position_short_name' => ' ', 'position_name' => 'Admin Asst. III (Computer Operator II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '9', 'position_short_name' => ' ', 'position_name' => 'Admin Officer II(Human Resource Management Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '10', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '11', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide I  (Utility Worker I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '12', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide I (Laborer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '13', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide I (Utility Worker I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '14', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '15', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide II (Messenger )', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '16', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide II (Messenger I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '17', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide II (Reproduction Machine Operator I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '18', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '19', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III (Carpenter I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '20', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III (Clerk I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '21', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III (Driver I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '22', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III (Laborer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '23', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III (Utility Worker II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '24', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III(Driver I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '25', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III(Laborer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '26', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide III(Utility Worker II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '27', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Accounting Clerk I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '28', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Bookbinder II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '29', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Cash Clerk I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '30', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Clerk II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '31', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Driver II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '32', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Electrician I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '33', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Mechanic I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '34', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Reproduction Machine Operator II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '35', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide IV (Stenographer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '36', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide V (Illustrator II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '37', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Accounting Clerk II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '38', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Artist Illustrator I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '39', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Cash Clerk II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '40', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Clerk III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '41', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Communication Equipment Operator II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '42', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Communications Equipment Operator II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '43', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Mechanic II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '44', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Storekeeper II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '45', 'position_short_name' => ' ', 'position_name' => 'Admin. Aide VI (Utility Foreman)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '46', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst.  II (Administrative Assistant)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '47', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. I (Audio-Visual Equipment Operator III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '48', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. I (Bookbinder III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '49', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II  (Cash Clerk III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '50', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II  (Clerk IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '51', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II  (Disbursing Officer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '52', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II (Administrative Assistant I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '53', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II (Administrative Assistant)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '54', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II (Bookkeeper I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '55', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II (Clerk IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '56', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II (Human Resource Management Assistant)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '57', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. II (Management & Audit Assistant)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '58', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. III (Buyer III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '59', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. III (Communications Equipment Operator III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '60', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. III (Computer Operator II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '61', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. III (Senior Bookkeeper )', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '62', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. III (Senior Bookkeeper)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '63', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. III (Storekeeper III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '64', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. V', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '65', 'position_short_name' => ' ', 'position_name' => 'Admin. Asst. VI (Computer Operator III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '66', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. I  (Cashier I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '67', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. I  (Records Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '68', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. I (Cashier I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '69', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. I (Records Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '70', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. I (Supply Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '71', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. II (Administrative Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '72', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. II (Human Resource Management Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '73', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. II (Information Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '74', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. II (Management & Audit Analyst I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '75', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. III (Cashier II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '76', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. III (Records Officer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '77', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. III (Suply Officer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '78', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. III (Supply Officer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '79', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. IV (Administrative Officer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '80', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. IV (Human Resource Management Officer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '81', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. IV (Management & Audit Analyst II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '82', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. V (Administrative Officer III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '83', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. V (Cashier III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '84', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. V (Human Resource Management Officer III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '85', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. V (Management & Audit Analyst III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '86', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. V (Records Officer III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '87', 'position_short_name' => ' ', 'position_name' => 'Admin. Off. V (Supply Officer III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '88', 'position_short_name' => ' ', 'position_name' => 'Admin. Officer II (Administrative Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '89', 'position_short_name' => ' ', 'position_name' => 'Admin. Officer II (Information Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '90', 'position_short_name' => ' ', 'position_name' => 'Admin. Officer IV (Information Officer II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '91', 'position_short_name' => ' ', 'position_name' => 'Admin. Officer V (Administrative Officer III)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '92', 'position_short_name' => ' ', 'position_name' => 'Admin. Officer V (Fiscal Examiner)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '93', 'position_short_name' => ' ', 'position_name' => 'Admin.Aide III (Clerk I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '94', 'position_short_name' => ' ', 'position_name' => 'Administrative Aide I (Utility Worker I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '95', 'position_short_name' => ' ', 'position_name' => 'Administrative Aide III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '96', 'position_short_name' => ' ', 'position_name' => 'Administrative Aide III (Utility Worker II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '97', 'position_short_name' => ' ', 'position_name' => 'Administrative Aide IV (Driver II)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '98', 'position_short_name' => ' ', 'position_name' => 'Administrative Aide VI  (Utility Foreman)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '99', 'position_short_name' => ' ', 'position_name' => 'Administrative Officer II (Administrative Officer I)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '100', 'position_short_name' => ' ', 'position_name' => 'Agricultural Center Chief I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '101', 'position_short_name' => ' ', 'position_name' => 'Agricultural Technologist', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '102', 'position_short_name' => ' ', 'position_name' => 'Agriculturist I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '103', 'position_short_name' => ' ', 'position_name' => 'Agriculturist II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '104', 'position_short_name' => ' ', 'position_name' => 'Aquaculturist I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '105', 'position_short_name' => ' ', 'position_name' => 'Aquaculturist II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '106', 'position_short_name' => ' ', 'position_name' => 'Architect III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '107', 'position_short_name' => ' ', 'position_name' => 'Assessment Clerk II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '108', 'position_short_name' => ' ', 'position_name' => 'Asst. Statistician', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '109', 'position_short_name' => ' ', 'position_name' => 'Bookbinder II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '110', 'position_short_name' => ' ', 'position_name' => 'Bookbinder III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '111', 'position_short_name' => ' ', 'position_name' => 'Budget Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '112', 'position_short_name' => ' ', 'position_name' => 'Budget Off. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '113', 'position_short_name' => ' ', 'position_name' => 'Budget Off. III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '114', 'position_short_name' => ' ', 'position_name' => 'Budget Off. IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '115', 'position_short_name' => ' ', 'position_name' => 'Budget Officer III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '116', 'position_short_name' => ' ', 'position_name' => 'Budgeting Asst.', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '117', 'position_short_name' => ' ', 'position_name' => 'Carpenter Foreman', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '118', 'position_short_name' => ' ', 'position_name' => 'Carpenter I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '119', 'position_short_name' => ' ', 'position_name' => 'Carpenter II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '120', 'position_short_name' => ' ', 'position_name' => 'Chauffeur II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '121', 'position_short_name' => ' ', 'position_name' => 'Chemist IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '122', 'position_short_name' => ' ', 'position_name' => 'Chief of Hospital ', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '123', 'position_short_name' => ' ', 'position_name' => 'Chief of Hospital I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '124', 'position_short_name' => ' ', 'position_name' => 'Community Affairs Off. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '125', 'position_short_name' => ' ', 'position_name' => 'Community Affairs Off. III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '126', 'position_short_name' => ' ', 'position_name' => "Community Dev't Asst.  I", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '127', 'position_short_name' => ' ', 'position_name' => "Community Dev't Asst.  II", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '128', 'position_short_name' => ' ', 'position_name' => "Community Dev't Asst. II", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '129', 'position_short_name' => ' ', 'position_name' => "Community Dev't Off. II", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '130', 'position_short_name' => ' ', 'position_name' => 'Computer Programmer III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '131', 'position_short_name' => ' ', 'position_name' => 'Const. & Maint. Capataz', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '132', 'position_short_name' => ' ', 'position_name' => 'Const. & Maint. Foreman', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '133', 'position_short_name' => ' ', 'position_name' => 'Const. & Maint. Gen. Foreman', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '134', 'position_short_name' => ' ', 'position_name' => 'Const. & Maint. Man', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '135', 'position_short_name' => ' ', 'position_name' => 'Cook I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '136', 'position_short_name' => ' ', 'position_name' => "Cooperative Dev't Specialist II", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '137', 'position_short_name' => ' ', 'position_name' => 'Crafts & Trade Helper', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '138', 'position_short_name' => ' ', 'position_name' => 'Dental Aide', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '139', 'position_short_name' => ' ', 'position_name' => 'Dentist II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '140', 'position_short_name' => ' ', 'position_name' => 'Dentist III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '141', 'position_short_name' => ' ', 'position_name' => 'Development Management Off. IV ', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '142', 'position_short_name' => ' ', 'position_name' => 'Development Management Officer III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '143', 'position_short_name' => ' ', 'position_name' => 'Development Management Officer IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '144', 'position_short_name' => ' ', 'position_name' => 'Disability Affairs Officer I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '145', 'position_short_name' => ' ', 'position_name' => 'Draftsman III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '146', 'position_short_name' => ' ', 'position_name' => 'Driver I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '147', 'position_short_name' => ' ', 'position_name' => 'Driver II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '148', 'position_short_name' => ' ', 'position_name' => 'Electrician II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '149', 'position_short_name' => ' ', 'position_name' => 'Electronics & Communications Equipment Technician I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '150', 'position_short_name' => ' ', 'position_name' => 'Engineer II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '151', 'position_short_name' => ' ', 'position_name' => 'Engineer III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '152', 'position_short_name' => ' ', 'position_name' => 'Engineer IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '153', 'position_short_name' => ' ', 'position_name' => 'Engineering Aide', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '154', 'position_short_name' => ' ', 'position_name' => 'Engineering Asst.', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '155', 'position_short_name' => ' ', 'position_name' => 'Executive Assistant II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '156', 'position_short_name' => ' ', 'position_name' => 'Executive Assistant III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '157', 'position_short_name' => ' ', 'position_name' => 'Executive Assistant IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '158', 'position_short_name' => ' ', 'position_name' => 'Farm Foreman', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '159', 'position_short_name' => ' ', 'position_name' => 'Farm Worker I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '160', 'position_short_name' => ' ', 'position_name' => 'Health Education & Promotion Off. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '161', 'position_short_name' => ' ', 'position_name' => 'Heavy Equipment Operator II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '162', 'position_short_name' => ' ', 'position_name' => 'Home Mgt. Tech.', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '163', 'position_short_name' => ' ', 'position_name' => 'Information Technology Officer II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '164', 'position_short_name' => ' ', 'position_name' => 'Instrumentman', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '165', 'position_short_name' => ' ', 'position_name' => 'Internal Auditor II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '166', 'position_short_name' => ' ', 'position_name' => 'Lab. Aide  II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '167', 'position_short_name' => ' ', 'position_name' => 'Lab. Aide II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '168', 'position_short_name' => ' ', 'position_name' => 'Lab. Inspector III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '169', 'position_short_name' => ' ', 'position_name' => 'Lab. Technician I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '170', 'position_short_name' => ' ', 'position_name' => 'Laboratory Aide II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '171', 'position_short_name' => ' ', 'position_name' => 'Laundry Worker I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '172', 'position_short_name' => ' ', 'position_name' => 'LDRRM Assistant', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '173', 'position_short_name' => ' ', 'position_name' => 'LDRRMO II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '174', 'position_short_name' => ' ', 'position_name' => 'LDRRMO III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '175', 'position_short_name' => ' ', 'position_name' => 'Legal Asst. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '176', 'position_short_name' => ' ', 'position_name' => 'Legal Asst. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '177', 'position_short_name' => ' ', 'position_name' => 'Local Assessment Operations Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '178', 'position_short_name' => ' ', 'position_name' => 'Local Assessment Operations Off. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '179', 'position_short_name' => ' ', 'position_name' => 'Local Assessment Operations Off. III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '180', 'position_short_name' => ' ', 'position_name' => 'Local Assessment Operations Off. IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '181', 'position_short_name' => ' ', 'position_name' => 'Local Assessment Operations Off.IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '182', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Asst.  II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '183', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Asst. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '184', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Asst. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '185', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Asst. III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '186', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Employee II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '187', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '188', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Off. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '189', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Off. III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '190', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Off. IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '191', 'position_short_name' => ' ', 'position_name' => 'Local Legislative Staff Off. V', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '192', 'position_short_name' => ' ', 'position_name' => 'Local Revenue Collection Officer II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '193', 'position_short_name' => ' ', 'position_name' => 'Local Revenue Collection Officer III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '194', 'position_short_name' => ' ', 'position_name' => 'Local Revenue Collection Officer IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '195', 'position_short_name' => ' ', 'position_name' => 'Local Treasury Operations Asst.', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '196', 'position_short_name' => ' ', 'position_name' => 'Local Treasury Operations Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '197', 'position_short_name' => ' ', 'position_name' => 'Local Treasury Operations Off. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '198', 'position_short_name' => ' ', 'position_name' => 'Local Treasury Operations Off. III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '199', 'position_short_name' => ' ', 'position_name' => 'Local Treasury Operations Off. IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '200', 'position_short_name' => ' ', 'position_name' => 'Local Treasury Operations Officer I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '201', 'position_short_name' => ' ', 'position_name' => 'Mason I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '202', 'position_short_name' => ' ', 'position_name' => 'Mason II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '203', 'position_short_name' => ' ', 'position_name' => 'Mechanic II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '204', 'position_short_name' => ' ', 'position_name' => 'Mechanic III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '205', 'position_short_name' => ' ', 'position_name' => 'Mechanical Plant Operator I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '206', 'position_short_name' => ' ', 'position_name' => 'Mechanical Shop  Foreman', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '207', 'position_short_name' => ' ', 'position_name' => 'Mechanical Shop Gen. Foreman', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '208', 'position_short_name' => ' ', 'position_name' => 'Med. Equipment Technician II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '209', 'position_short_name' => ' ', 'position_name' => 'Med. Equipt. Technician II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '210', 'position_short_name' => ' ', 'position_name' => 'Med. Specialist III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '211', 'position_short_name' => ' ', 'position_name' => 'Med. Tech. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '212', 'position_short_name' => ' ', 'position_name' => 'Medical Officer III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '213', 'position_short_name' => ' ', 'position_name' => 'Medical Officer Ill', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '214', 'position_short_name' => ' ', 'position_name' => 'Medical Officer IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '215', 'position_short_name' => ' ', 'position_name' => 'Medical Officer lV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '216', 'position_short_name' => ' ', 'position_name' => 'Medical Technologist', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '217', 'position_short_name' => ' ', 'position_name' => 'Medical Technologist I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '218', 'position_short_name' => ' ', 'position_name' => 'Medical Technologist II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '219', 'position_short_name' => ' ', 'position_name' => 'Metal Worker I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '220', 'position_short_name' => ' ', 'position_name' => 'Midwife I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '221', 'position_short_name' => ' ', 'position_name' => 'Midwife II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '222', 'position_short_name' => ' ', 'position_name' => 'Midwife III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '223', 'position_short_name' => ' ', 'position_name' => 'Midwife IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '224', 'position_short_name' => ' ', 'position_name' => 'Nurse I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '225', 'position_short_name' => ' ', 'position_name' => 'Nurse II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '226', 'position_short_name' => ' ', 'position_name' => 'Nurse IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '227', 'position_short_name' => ' ', 'position_name' => 'Nursing Attendant I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '228', 'position_short_name' => ' ', 'position_name' => 'Nursing Attendant II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '229', 'position_short_name' => ' ', 'position_name' => 'Nutrition Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '230', 'position_short_name' => ' ', 'position_name' => 'Nutrition Officer I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '231', 'position_short_name' => ' ', 'position_name' => 'Nutrition Officer II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '232', 'position_short_name' => ' ', 'position_name' => 'Nutrition Officer III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '233', 'position_short_name' => ' ', 'position_name' => 'Nutrition Officer IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '234', 'position_short_name' => ' ', 'position_name' => 'Nutritionist Dietitian II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '235', 'position_short_name' => ' ', 'position_name' => 'Nutritionist-Dietitian I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '236', 'position_short_name' => ' ', 'position_name' => 'Nutritionist-Dietitian II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '237', 'position_short_name' => ' ', 'position_name' => 'Painter II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '238', 'position_short_name' => ' ', 'position_name' => 'PG II/Wardress II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '239', 'position_short_name' => ' ', 'position_name' => 'PGADH  (Asst. Provincial Administrator )', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '240', 'position_short_name' => ' ', 'position_name' => 'PGADH  (Asst. Provincial Human Resource Management Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '241', 'position_short_name' => ' ', 'position_name' => "PGADH  (Prov'l Health Officer I)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '242', 'position_short_name' => ' ', 'position_name' => 'PGADH (Asst. PDRRM Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '243', 'position_short_name' => ' ', 'position_name' => 'PGADH (Asst. Provincial Accountant)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '244', 'position_short_name' => ' ', 'position_name' => 'PGADH (Asst. Provincial Agriculturist)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '245', 'position_short_name' => ' ', 'position_name' => 'PGADH (Asst. Provincial Assessor)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '246', 'position_short_name' => ' ', 'position_name' => 'PGADH (Asst. Provincial Budget Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '247', 'position_short_name' => ' ', 'position_name' => 'PGADH (Asst. Provincial Engineer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '248', 'position_short_name' => ' ', 'position_name' => 'PGADH (Asst. Provincial Treasurer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '249', 'position_short_name' => ' ', 'position_name' => "PGADH (Asst. Prov'l Envi. & Natural Resources Officer)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '250', 'position_short_name' => ' ', 'position_name' => "PGADH (Asst. Prov'l Planning & Dev't. Coordinator)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '251', 'position_short_name' => ' ', 'position_name' => 'PGADH (Asst. Sec. to the SP)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '252', 'position_short_name' => ' ', 'position_name' => "PGADH(Asst. Prov'l General Services Off.)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '253', 'position_short_name' => ' ', 'position_name' => 'PGDH  (Provincial Accountant)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '254', 'position_short_name' => ' ', 'position_name' => 'PGDH  (Provincial Fisheries & Aquatic Resources Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '255', 'position_short_name' => ' ', 'position_name' => 'PGDH  (Provincial Social Welfare & Development Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '256', 'position_short_name' => ' ', 'position_name' => 'PGDH  (Provincial Veterinarian)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '257', 'position_short_name' => ' ', 'position_name' => "PGDH  (Prov'l Envi. & Natural Resources Officer)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '258', 'position_short_name' => ' ', 'position_name' => "PGDH  (Prov'l Health Officer II)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '259', 'position_short_name' => ' ', 'position_name' => "PGDH (PDRRM Officer)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '260', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Administrator )', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '261', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Agriculturist)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '262', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Assessor)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '263', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Budget Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '264', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Engineer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '265', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Human Resource Management Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '266', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Internal Auditor)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '267', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Legal Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '268', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Tourism Officer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '269', 'position_short_name' => ' ', 'position_name' => 'PGDH (Provincial Treasurer)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '270', 'position_short_name' => ' ', 'position_name' => "PGDH (Prov'l Planning & Dev't. Coordinator)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '271', 'position_short_name' => ' ', 'position_name' => 'PGDH (Sec. to the SP)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '272', 'position_short_name' => ' ', 'position_name' => "PGDH(Prov'l General Services Off.)", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '273', 'position_short_name' => ' ', 'position_name' => 'Pharmacist I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '274', 'position_short_name' => ' ', 'position_name' => 'Pharmacist II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '275', 'position_short_name' => ' ', 'position_name' => 'Planning Asst.', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '276', 'position_short_name' => ' ', 'position_name' => 'Planning Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '277', 'position_short_name' => ' ', 'position_name' => 'Planning Off. II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '278', 'position_short_name' => ' ', 'position_name' => 'Planning Off. III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '279', 'position_short_name' => ' ', 'position_name' => 'Planning Off. IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '280', 'position_short_name' => ' ', 'position_name' => 'Pop. Prog. Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '281', 'position_short_name' => ' ', 'position_name' => 'Pop. Prog. Off. IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '282', 'position_short_name' => ' ', 'position_name' => 'Pop. Prog. Worker II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '283', 'position_short_name' => ' ', 'position_name' => 'Prison Guard I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '284', 'position_short_name' => ' ', 'position_name' => 'Prison Guard II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '285', 'position_short_name' => ' ', 'position_name' => 'Prison Guard III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '286', 'position_short_name' => ' ', 'position_name' => 'Private Secretary I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '287', 'position_short_name' => ' ', 'position_name' => 'Private Secretary II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '288', 'position_short_name' => ' ', 'position_name' => "Proj. Dev't Off. I", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '289', 'position_short_name' => ' ', 'position_name' => "Proj. Dev't Off. II", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '290', 'position_short_name' => ' ', 'position_name' => "Proj. Dev't Off. IV", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '291', 'position_short_name' => ' ', 'position_name' => 'Proj. Evaluation Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '292', 'position_short_name' => ' ', 'position_name' => 'Proj. Evaluation Off. III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '293', 'position_short_name' => ' ', 'position_name' => 'Proj. Evaluation Off. IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '294', 'position_short_name' => ' ', 'position_name' => "Proj.Dev't Off. III", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '295', 'position_short_name' => ' ', 'position_name' => 'Provincial Governor', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '296', 'position_short_name' => ' ', 'position_name' => 'Provincial Warden', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '297', 'position_short_name' => ' ', 'position_name' => "Prov'l Vice Governor", 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '298', 'position_short_name' => ' ', 'position_name' => 'Radiologic Technologist I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '299', 'position_short_name' => ' ', 'position_name' => 'Radiologic Technologist II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '300', 'position_short_name' => ' ', 'position_name' => 'Revenue Collection Clerk II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '301', 'position_short_name' => ' ', 'position_name' => 'Sanitation Inspector II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '302', 'position_short_name' => ' ', 'position_name' => 'Sanitation Inspector III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '303', 'position_short_name' => ' ', 'position_name' => 'Sanitation Inspector IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '304', 'position_short_name' => ' ', 'position_name' => 'Secretary I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '305', 'position_short_name' => ' ', 'position_name' => 'Security Agent II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '306', 'position_short_name' => ' ', 'position_name' => 'Security Guard I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '307', 'position_short_name' => ' ', 'position_name' => 'Security Guard II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '308', 'position_short_name' => ' ', 'position_name' => 'Security Guard III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '309', 'position_short_name' => ' ', 'position_name' => 'Security Off. IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '310', 'position_short_name' => ' ', 'position_name' => 'Security Officer I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '311', 'position_short_name' => ' ', 'position_name' => 'Security Officer II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '312', 'position_short_name' => ' ', 'position_name' => 'Senior Admin Asst. II (Computer Operator IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '313', 'position_short_name' => ' ', 'position_name' => 'Senior Administrative Asst. II (Computer Operator IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '314', 'position_short_name' => ' ', 'position_name' => 'Senior Home Mgt. Specialist', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '315', 'position_short_name' => ' ', 'position_name' => 'Senior Tourism Operations Officer', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '316', 'position_short_name' => ' ', 'position_name' => 'Social Welfare Asst.', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '317', 'position_short_name' => ' ', 'position_name' => 'Social Welfare Officer I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '318', 'position_short_name' => ' ', 'position_name' => 'Social Welfare Officer II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '319', 'position_short_name' => ' ', 'position_name' => 'Social Welfare Officer III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '320', 'position_short_name' => ' ', 'position_name' => 'SP Member', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '321', 'position_short_name' => ' ', 'position_name' => 'Special Agent I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '322', 'position_short_name' => ' ', 'position_name' => 'Sport & Games Regulation Off. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '323', 'position_short_name' => ' ', 'position_name' => 'Sr. Admin. Asst. I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '324', 'position_short_name' => ' ', 'position_name' => 'Sr. Admin. Asst. II (Computer Operator IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '325', 'position_short_name' => ' ', 'position_name' => 'Sr. Agriculturist', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '326', 'position_short_name' => ' ', 'position_name' => 'Statistician Aide', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '327', 'position_short_name' => ' ', 'position_name' => 'Statistician I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '328', 'position_short_name' => ' ', 'position_name' => 'Storekeeper II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '329', 'position_short_name' => ' ', 'position_name' => 'Supervising Admin. Off. (Administrative Officer IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '330', 'position_short_name' => ' ', 'position_name' => 'Supervising Admin. Off. (Cashier IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '331', 'position_short_name' => ' ', 'position_name' => 'Supervising Admin. Off. (Human Resource Management Officer IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '332', 'position_short_name' => ' ', 'position_name' => 'Supervising Admin. Off. (Management & Audit Analyst IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '333', 'position_short_name' => ' ', 'position_name' => 'Supervising Admin. Off. (Supply Officer IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '334', 'position_short_name' => ' ', 'position_name' => 'Supervising Admin. Officer (Administrative Officer IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '335', 'position_short_name' => ' ', 'position_name' => 'Supervising Administrative Officer (Administrative Officer IV)', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '336', 'position_short_name' => ' ', 'position_name' => 'Supervising Agriculturist', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '337', 'position_short_name' => ' ', 'position_name' => 'Supervising Aquaculturist ', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '338', 'position_short_name' => ' ', 'position_name' => 'Supervising Home Mgt. Specialist', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '339', 'position_short_name' => ' ', 'position_name' => 'Supervising Tourism Operations Off.', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '340', 'position_short_name' => ' ', 'position_name' => 'Tax Mapper II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '341', 'position_short_name' => ' ', 'position_name' => 'Tax Mapper III', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '342', 'position_short_name' => ' ', 'position_name' => 'Tax Mapper IV', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '343', 'position_short_name' => ' ', 'position_name' => 'Ticket Checker', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '344', 'position_short_name' => ' ', 'position_name' => 'Tourism Operations Officer II', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '345', 'position_short_name' => ' ', 'position_name' => 'Welder I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '346', 'position_short_name' => ' ', 'position_name' => 'Health Program Officer I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),
            array('code' => '347', 'position_short_name' => ' ', 'position_name' => 'Executive Assistant I', 'created_at' => Carbon::now() ,'updated_at' => Carbon::now()),

         );
         DB::table('positions')->insert($positions);
        // Position::create([
        //     'code'  =>  '1001',
        //     'position_name'  =>  'Human Resource Officer',
        //     'position_short_name'  =>  'HRMO',
        // ]);
    }
}
